repos:
- repo: https://github.com/psf/black
  rev: 23.12.1
  hooks:
  - id: black
    name: black
    description: "Black: The uncompromising Python code formatter"
    entry: black
    language: python
    language_version: python3
    minimum_pre_commit_version: 2.9.2
    require_serial: true
    types_or: [python, pyi]
  - id: black-jupyter
    name: black-jupyter
    description:
      "Black: The uncompromising Python code formatter (with Jupyter Notebook support)"
    entry: black
    language: python
    minimum_pre_commit_version: 2.9.2
    require_serial: true
    types_or: [python, pyi, jupyter]
    additional_dependencies: [".[jupyter]"]

- repo: https://github.com/pycqa/flake8
  rev: 7.0.0
  hooks:
  - id: flake8
    additional_dependencies:
    - flake8-bugbear
    - flake8-comprehensions
    - flake8-simplify

- repo: https://gitlab.com/kennon.mckeever/nbhooks
  rev: 1.0.1
  hooks:
  - id: nb-ensure-clean
    name: nb-ensure-clean
    description: Ensure that committed Jupyter notebooks contain no outputs.
    entry: nb-ensure-clean
    files: \.ipynb$
    language: python

- repo: https://github.com/asottile/pyupgrade
  rev: v3.15.0
  hooks:
  - id: pyupgrade
    args: [--py310-plus]

- repo: https://github.com/asottile/reorder-python-imports
  rev: v3.12.0
  hooks:
  - id: reorder-python-imports
    args: [--py310-plus, --add-import, "from __future__ import annotations"]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: check-builtin-literals
    - id: check-added-large-files
    - id: check-case-conflict
    - id: check-toml
    - id: check-yaml
    - id: debug-statements
    - id: end-of-file-fixer
    - id: forbid-new-submodules
    - id: mixed-line-ending
    - id: trailing-whitespace
    - id: name-tests-test
    - id: file-contents-sorter
      files: requirements.in|.gitignore

- repo: https://github.com/regebro/pyroma
  rev: "4.2"
  hooks:
  - id: pyroma
    args: ["-d", "--min=10", "."]
    additional_dependencies:
    - numpy
    - cython

- repo: https://github.com/PyCQA/pydocstyle
  rev: 6.3.0
  hooks:
  - id: pydocstyle
    files: bmipy/.*\.py$
    args:
    - --convention=numpy
    - --add-select=D417
    additional_dependencies: [".[toml]"]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.8.0
  hooks:
  - id: mypy
    language_version: python3.12
    additional_dependencies: [types-all]
    files: src/.*\.py$
